---

grafana:
  service:
    type: NodePort
    nodePort: 32000
  resources:
    requests:
      memory: 512Mi
  grafana.ini:
    database:
      cache_mode: "private"
    analytics:
      reporting_enabled: false

---
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 24h
    retentionSize: 1GB
    resources:
      requests:
        memory: 512Mi
    scrapeInterval: 30s
    evaluationInterval: 30s
