apiVersion: operator.tigera.io/v1
kind: Goldmane
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.tigera.io/v1","kind":"Goldmane","metadata":{"annotations":{},"name":"default"}}
  creationTimestamp: "2025-12-02T21:08:14Z"
  generation: 1
  name: default
  resourceVersion: "7262"
  uid: 11aeb072-2472-4ec8-b055-f916f79b121a
