apiVersion: v1
items:
- apiVersion: operator.tigera.io/v1
  kind: Installation
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"Installation","metadata":{"annotations":{},"name":"default"},"spec":{"calicoNetwork":{"ipPools":[{"blockSize":24,"cidr":"192.168.0.0/24","encapsulation":"VXLAN","name":"default-ipv4-ippool","natOutgoing":"Enabled","nodeSelector":"all()"}],"nodeAddressAutodetectionV4":{"interface":"eth0"}}}}
    creationTimestamp: "2025-12-02T21:08:14Z"
    finalizers:
    - operator.tigera.io/installation-controller
    - tigera.io/operator-cleanup
    - operator.tigera.io/apiserver-controller
    generation: 17
    name: default
    resourceVersion: "4534030"
    uid: 22371791-08d0-4611-b7c8-460f1d5583ae
  spec:
    calicoNetwork:
      bgp: Enabled
      hostPorts: Enabled
      ipPools:
      - allowedUses:
        - Workload
        - Tunnel
        assignmentMode: Automatic
        blockSize: 24
        cidr: 192.168.0.0/24
        disableBGPExport: false
        disableNewAllocations: false
        encapsulation: VXLAN
        name: default-ipv4-ippool
        natOutgoing: Enabled
        nodeSelector: all()
      linuxDataplane: Iptables
      linuxPolicySetupTimeoutSeconds: 0
      multiInterfaceMode: None
      nodeAddressAutodetectionV4:
        firstFound: true
        interface: eth0
      windowsDataplane: Disabled
    cni:
      ipam:
        type: Calico
      type: Calico
    controlPlaneReplicas: 2
    flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
    kubeletVolumePluginPath: /var/lib/kubelet
    logging:
      cni:
        logFileMaxAgeDays: 30
        logFileMaxCount: 10
        logFileMaxSize: 100Mi
        logSeverity: Info
    nodeUpdateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
    nonPrivileged: Disabled
    variant: Calico
  status:
    calicoVersion: v3.30.0
    computed:
      calicoNetwork:
        bgp: Enabled
        hostPorts: Enabled
        ipPools:
        - allowedUses:
          - Workload
          - Tunnel
          assignmentMode: Automatic
          blockSize: 24
          cidr: 192.168.0.0/24
          disableBGPExport: false
          disableNewAllocations: false
          encapsulation: VXLANCrossSubnet
          name: default-ipv4-ippool
          natOutgoing: Enabled
          nodeSelector: all()
        linuxDataplane: Iptables
        linuxPolicySetupTimeoutSeconds: 0
        multiInterfaceMode: None
        nodeAddressAutodetectionV4:
          firstFound: true
        windowsDataplane: Disabled
      cni:
        ipam:
          type: Calico
        type: Calico
      controlPlaneReplicas: 2
      flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
      kubeletVolumePluginPath: /var/lib/kubelet
      logging:
        cni:
          logFileMaxAgeDays: 30
          logFileMaxCount: 10
          logFileMaxSize: 100Mi
          logSeverity: Info
      nodeUpdateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      nonPrivileged: Disabled
      variant: Calico
    conditions:
    - lastTransitionTime: "2025-12-27T05:35:29Z"
      message: 'Invalid Installation provided: no more than one node address autodetection
        method can be specified per-family'
      observedGeneration: 17
      reason: InvalidConfigurationError
      status: "True"
      type: Degraded
    - lastTransitionTime: "2025-12-27T05:35:29Z"
      message: ""
      observedGeneration: 15
      reason: Unknown
      status: "False"
      type: Ready
    - lastTransitionTime: "2025-12-27T05:35:29Z"
      message: ""
      observedGeneration: 15
      reason: Unknown
      status: "False"
      type: Progressing
    mtu: 1450
    variant: Calico
kind: List
metadata:
  resourceVersion: ""
