apiVersion: v1
items:
- apiVersion: operator.tigera.io/v1
  kind: Whisker
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operator.tigera.io/v1","kind":"Whisker","metadata":{"annotations":{},"name":"default"}}
    creationTimestamp: "2025-12-02T21:08:14Z"
    generation: 2
    name: default
    resourceVersion: "7265"
    uid: 264a409d-51c5-4cf4-a264-4711a5736ad8
  spec:
    notifications: Enabled
kind: List
metadata:
  resourceVersion: ""
